var_for_docker_image: &docker_image circleci/python:2.7.14-jessie-browsers

anchor_for_job_defaults: &job_defaults
  working_directory: /home/circleci/oppia
  docker:
    - image: *docker_image

anchor_for_installing_dependencies: &install_dependencies
  name: Install dependencies
  command: |
    source scripts/setup.sh || exit 1
    source scripts/setup_gae.sh || exit 1

anchor_for_restoring_cache: &restore_cache
  keys:
    - setup-files-cache
    - third-party-cache

version: 2
jobs:
  setup:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          <<: *install_dependencies
      - save_cache:
          key: setup-files-cache
          paths:
            - ../node_modules/
            - ../oppia_tools/

  lint_tests:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Run lint tests
          command: |
            bash scripts/install_third_party.sh
            python scripts/third_party_size_check.py
            python scripts/pre_commit_linter.py --path=.
      - save_cache:
          key: third-party-cache
          paths:
            - third_party/

  frontend_tests:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Run frontend tests
          command: |
            bash -x scripts/run_frontend_tests.sh --run-minified-tests=true

  backend_tests:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          <<: *restore_cache
      - run:
          name: Run backend tests
          command: |
            bash scripts/run_backend_tests.sh --exclude_load_tests

workflows:
  version: 2
  circleci_tests:
    jobs:
      - setup
      - lint_tests:
          requires:
            - setup
      # - frontend_tests:
      #     requires:
      #       - setup
      # - backend_tests:
      #     requires:
      #       - setup
